### ISSUE TITLE
Schaltplan als PDF

### ISSUE THREAD

**Issue by ghost** [Infinitag/Hardware#1]
Ich würde mir gerne euren Schaltplan anschauen. KiCad habe ich bis jetzt ehrlich gesagt noch nicht verstanden. Könntet ihr bitte eine PDF des Schaltplans hochladen?

**Comment by syrix85** [comment]
Hallo, leider sind unsere Pläne auch noch nicht fehlerfrei und daher nicht wirklich online. Sobald wir was rundes und funktionierendes haben, sehen wir mal weiter ;)
